=== wissem007/badges/WebRoot/WEB-INF/classes/tn/com/smartsoft/ressources/xsd/beans.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="tn.com.smartsoft.framework.configuration.definition.BeansDefinition">
   <xsd:sequence>
    <xsd:element name="variable-system" minOccurs="0" maxOccurs="unbounded">
     <xsd:complexType>
      <xsd:attribute name="name" type="xsd:string" use="optional">
      </xsd:attribute>
      <xsd:attribute name="value" type="xsd:string" use="optional">
      </xsd:attribute>
     </xsd:complexType>
    </xsd:element>
    <xsd:element name="bean" type="tn.com.smartsoft.framework.beans.definition.BeanDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="dao-bean" type="tn.com.smartsoft.framework.dao.definition.DaoBeanDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="dao-parse-bean" type="tn.com.smartsoft.framework.dao.definition.DaoParseBeanDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="business-bean" type="tn.com.smartsoft.framework.business.definition.BusinessBeanDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="controler-bean" type="tn.com.smartsoft.framework.presentation.definition.ControleBeanDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="user-action-bean" type="tn.com.smartsoft.framework.presentation.definition.UserActionDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="binding-model" type="tn.com.smartsoft.framework.presentation.definition.BindingModelDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="window" type="tn.com.smartsoft.framework.presentation.definition.WindowDefinition" minOccurs="0" maxOccurs="unbounded"/>
   </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.beans.definition.BeanDefinition">
   <xsd:sequence>
    <xsd:element name="set-property" type="tn.com.smartsoft.framework.beans.definition.PropertyDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="set-map" type="tn.com.smartsoft.framework.beans.definition.MapPropertyDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="set-list" type="tn.com.smartsoft.framework.beans.definition.ListPropertyDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="set-component-id" type="tn.com.smartsoft.framework.beans.definition.ComponentIdDefinition" minOccurs="0" maxOccurs="unbounded"/>
   </xsd:sequence>
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="class" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.beans.definition.PropertyDefinition">
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="value" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="ref" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.beans.definition.MapPropertyDefinition">
   <xsd:sequence>
    <xsd:element name="add" type="tn.com.smartsoft.framework.beans.definition.MapEntryDefinition" minOccurs="0" maxOccurs="unbounded"/>
   </xsd:sequence>
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="type" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="key-type" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.beans.definition.MapEntryDefinition">
   <xsd:attribute name="key" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="value" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="type" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="ref" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.beans.definition.ListPropertyDefinition">
   <xsd:sequence>
    <xsd:element name="add" type="tn.com.smartsoft.framework.beans.definition.ListEntryDefinition" minOccurs="0" maxOccurs="unbounded"/>
   </xsd:sequence>
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="type" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.beans.definition.ListEntryDefinition">
   <xsd:attribute name="value" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="type" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="ref" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.beans.definition.ComponentIdDefinition">
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="id" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.dao.definition.DaoBeanDefinition">
   <xsd:sequence>
    <xsd:element name="query-method" type="tn.com.smartsoft.framework.dao.definition.DaoQueryMethodDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="sql-query-method" type="tn.com.smartsoft.framework.dao.definition.DaoSqlQueryMethodDefinition" minOccurs="0" maxOccurs="unbounded"/>
   </xsd:sequence>
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="interface" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.dao.definition.DaoQueryMethodDefinition">
   <xsd:sequence>
    <xsd:element name="query" minOccurs="0" maxOccurs="1">
     <xsd:complexType>
      <xsd:attribute name="value" type="xsd:string" use="required">
      </xsd:attribute>
     </xsd:complexType>
    </xsd:element>
    <xsd:element name="accessor" type="tn.com.smartsoft.framework.dao.definition.DbQueryAccessorDefinition" minOccurs="0" maxOccurs="1"/>
   </xsd:sequence>
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="is-updater" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="dao-parse-bean" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="class-resultat" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="session-arg-rang" type="xsd:int" use="optional">
   </xsd:attribute>
   <xsd:attribute name="prefix-arg-name" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.dao.definition.DbQueryAccessorDefinition">
   <xsd:sequence>
    <xsd:element name="lock-mode" minOccurs="0" maxOccurs="unbounded">
     <xsd:complexType>
      <xsd:attribute name="alias" type="xsd:string" use="optional">
      </xsd:attribute>
      <xsd:attribute name="mode" type="xsd:string" use="optional">
      </xsd:attribute>
     </xsd:complexType>
    </xsd:element>
   </xsd:sequence>
   <xsd:attribute name="cached" use="optional">
   </xsd:attribute>
   <xsd:attribute name="fetch-size" use="optional">
   </xsd:attribute>
   <xsd:attribute name="max-results" use="optional">
   </xsd:attribute>
   <xsd:attribute name="cache-region" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.dao.definition.DaoSqlQueryMethodDefinition">
   <xsd:sequence>
    <xsd:element name="query" minOccurs="0" maxOccurs="1">
     <xsd:complexType>
      <xsd:attribute name="value" type="xsd:string" use="required">
      </xsd:attribute>
     </xsd:complexType>
    </xsd:element>
    <xsd:element name="accessor" type="tn.com.smartsoft.framework.dao.definition.DbQueryAccessorDefinition" minOccurs="0" maxOccurs="1"/>
   </xsd:sequence>
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="is-updater" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="dao-parse-bean" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="class-resultat" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="session-arg-rang" type="xsd:int" use="optional">
   </xsd:attribute>
   <xsd:attribute name="prefix-arg-name" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.dao.definition.DaoParseBeanDefinition">
   <xsd:sequence>
    <xsd:element name="dao-parse-bean" type="tn.com.smartsoft.framework.dao.definition.DaoParseBeanDefinition" minOccurs="0" maxOccurs="unbounded"/>
   </xsd:sequence>
   <xsd:attribute name="id" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="property" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="recursive" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.business.definition.BusinessBeanDefinition">
   <xsd:sequence>
    <xsd:element name="set-dao-session" type="tn.com.smartsoft.framework.business.definition.DaoSessionRefDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="set-dao-bean" type="tn.com.smartsoft.framework.business.definition.DaoBeanRefDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="set-dao-parse-bean" type="tn.com.smartsoft.framework.business.definition.DaoParseBeanRefDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="set-property" type="tn.com.smartsoft.framework.beans.definition.PropertyDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="set-map" type="tn.com.smartsoft.framework.beans.definition.MapPropertyDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="set-list" type="tn.com.smartsoft.framework.beans.definition.ListPropertyDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="set-component-id" type="tn.com.smartsoft.framework.beans.definition.ComponentIdDefinition" minOccurs="0" maxOccurs="unbounded"/>
   </xsd:sequence>
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="class" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.business.definition.DaoSessionRefDefinition">
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="data-source-name" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.business.definition.DaoBeanRefDefinition">
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="ref" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="sujet" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="sub-module" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="module" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.business.definition.DaoParseBeanRefDefinition">
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="ref" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="sujet" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="sub-module" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="module" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.presentation.definition.ControleBeanDefinition">
   <xsd:sequence>
    <xsd:element name="set-business-bean" type="tn.com.smartsoft.framework.business.definition.BusinessBeanRefDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="set-property" type="tn.com.smartsoft.framework.beans.definition.PropertyDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="set-map" type="tn.com.smartsoft.framework.beans.definition.MapPropertyDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="set-list" type="tn.com.smartsoft.framework.beans.definition.ListPropertyDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="set-component-id" type="tn.com.smartsoft.framework.beans.definition.ComponentIdDefinition" minOccurs="0" maxOccurs="unbounded"/>
   </xsd:sequence>
   <xsd:attribute name="extends" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="class" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.business.definition.BusinessBeanRefDefinition">
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="ref" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="sujet" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="sub-module" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="module" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.presentation.definition.UserActionDefinition">
   <xsd:sequence>
    <xsd:element name="parameter" minOccurs="0" maxOccurs="unbounded">
     <xsd:complexType>
      <xsd:attribute name="name" type="xsd:string" use="optional">
      </xsd:attribute>
      <xsd:attribute name="value" type="xsd:string" use="optional">
      </xsd:attribute>
     </xsd:complexType>
    </xsd:element>
    <xsd:element name="binding-model" type="tn.com.smartsoft.framework.presentation.definition.BindingModelDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="binding-model-ref" type="tn.com.smartsoft.framework.presentation.definition.BindingRefModelDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="binding-property-model" type="tn.com.smartsoft.framework.presentation.definition.BindingPropertyModelDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="window" type="tn.com.smartsoft.framework.presentation.definition.WindowDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="window-ref" type="tn.com.smartsoft.framework.presentation.definition.WindowRefDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="report" type="tn.com.smartsoft.framework.presentation.definition.ReportDefinition" minOccurs="0" maxOccurs="unbounded"/>
   </xsd:sequence>
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="extends" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="model-class" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="controler-bean" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="home-window-id" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="on-home-methode" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.presentation.definition.BindingModelDefinition">
   <xsd:sequence>
    <xsd:element name="binding-model" type="tn.com.smartsoft.framework.presentation.definition.BindingModelDefinition" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element name="binding-property-model" type="tn.com.smartsoft.framework.presentation.definition.BindingPropertyModelDefinition" minOccurs="0" maxOccurs="unbounded"/>
   </xsd:sequence>
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="type" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="mode" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.presentation.definition.BindingPropertyModelDefinition">
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="type" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="mode" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="libelle-exp" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="user-type" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.presentation.definition.BindingRefModelDefinition">
   <xsd:attribute name="name" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="ref" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.presentation.definition.WindowDefinition">
   <xsd:sequence>
    <xsd:element name="parameter" minOccurs="0" maxOccurs="unbounded">
     <xsd:complexType>
      <xsd:attribute name="name" type="xsd:string" use="optional">
      </xsd:attribute>
      <xsd:attribute name="value" type="xsd:string" use="optional">
      </xsd:attribute>
     </xsd:complexType>
    </xsd:element>
   </xsd:sequence>
   <xsd:attribute name="id" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="location" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="view-id" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="on-init-methode" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="on-render-methode" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="on-security-check-methode" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="on-destroy-methode" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.presentation.definition.WindowRefDefinition">
   <xsd:attribute name="id" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="ref" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:complexType name="tn.com.smartsoft.framework.presentation.definition.ReportDefinition">
   <xsd:attribute name="id" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="location" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="ds-property" type="xsd:string" use="optional">
   </xsd:attribute>
   <xsd:attribute name="type" type="xsd:string" use="optional">
   </xsd:attribute>
  </xsd:complexType>
  <xsd:element name="beans" type="tn.com.smartsoft.framework.configuration.definition.BeansDefinition"/>
 </xsd:schema>

=== wissem007/badges/WebRoot/WEB-INF/classes/tn/com/smartsoft/iap/system/system.beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xsi:noNamespaceSchemaLocation="../../ressources/xsd/beans.xsd">
	<variable-system name="beanDecoupagePack" value="tn.com.smartsoft.iap.dictionary.decoupage" />
	<variable-system name="beanSecuritePack" value="tn.com.smartsoft.iap.dictionary.securite.role.beans" />
	<variable-system name="beanGraphiquePack" value="tn.com.smartsoft.iap.dictionary.graphique" />
	<variable-system name="beanDevisePack" value="tn.com.smartsoft.configGenerale.devises.devise.beans" />
	<variable-system name="beanUserPack" value="tn.com.smartsoft.iap.administration.securite.utilisateur.beans" />
	<variable-system name="businessPack" value="tn.com.smartsoft.iap.system.business" />
	<variable-system name="daoPack" value="tn.com.smartsoft.iap.system.dao" />
	<variable-system name="modelPack" value="tn.com.smartsoft.iap.system.presentation.model" />
	<variable-system name="controlerPack" value="tn.com.smartsoft.iap.system.presentation.controler" />
	<variable-system name="viewPack" value="tn/com/smartsoft/iap/system/presentation/view" />
	<bean name="passwordHashing" class="${businessPack}.DefaultPasswordHashing"></bean>
	<dao-parse-bean id="menu"></dao-parse-bean>
	<dao-parse-bean id="view"></dao-parse-bean>
	<dao-parse-bean id="entite"></dao-parse-bean>
	<dao-parse-bean id="actionToolbar">
		<dao-parse-bean property="action">
			<dao-parse-bean property="actionTemplate"></dao-parse-bean>
		</dao-parse-bean>
	</dao-parse-bean>
	<dao-parse-bean id="userParser">
		<dao-parse-bean property="preferences"></dao-parse-bean>
		<dao-parse-bean property="autorisationOrg"></dao-parse-bean>
	</dao-parse-bean>
	<dao-bean name="applicationDictionnaireDao" interface="${daoPack}.ApplicationDictionnaireDao">
		<query-method name="getEntiteDictionary">
			<query>
        <![CDATA[
        SELECT  entite FROM ${beanDecoupagePack}.entite.beans.EntiteBean AS entite left join fetch entite.parentSujet
       ]]>
			</query>
		</query-method>
		<query-method name="getPropertyDictionary">
			<query>
        <![CDATA[
        SELECT  property FROM ${beanDecoupagePack}.entite.beans.PropertyBean AS property  left join fetch property.sequence
       ]]>
			</query>
		</query-method>
		<query-method name="getActionDictionary">
			<query>
        <![CDATA[
        SELECT  action FROM ${beanDecoupagePack}.action.beans.ActionBean AS action
       ]]>
			</query>
		</query-method>
		<query-method name="getModuleDictionary">
			<query>
        <![CDATA[
        SELECT  module FROM ${beanDecoupagePack}.module.beans.ModuleBean AS module where module.activate=true 
       ]]>
			</query>
		</query-method>
		<query-method name="getSubModuleDictionary">
			<query>
        <![CDATA[
        SELECT  subModule FROM ${beanDecoupagePack}.subModule.beans.SubModuleBean AS subModule
       ]]>
			</query>
		</query-method>
		<query-method name="getViewDictionary">
			<query>
        <![CDATA[
        SELECT  view FROM ${beanGraphiquePack}.vue.beans.ViewBean AS view
       ]]>
			</query>
		</query-method>
		<query-method name="getViewLibelleDictionary">
			<query>
        <![CDATA[
        SELECT  viewLibelle FROM ${beanGraphiquePack}.vue.beans.ViewLibelleBean AS viewLibelle
       ]]>
			</query>
		</query-method>
		<query-method name="getViewActionDictionary">
			<query>
        <![CDATA[
        SELECT  viewAction FROM ${beanGraphiquePack}.vue.beans.ViewActionBean AS viewAction
       ]]>
			</query>
		</query-method>
		<query-method name="getLibelleDictionary">
			<query>
        <![CDATA[
        SELECT  applicationLibelle FROM ${beanGraphiquePack}.libelle.beans.LibelleBean AS applicationLibelle
       ]]>
			</query>
		</query-method>
		<query-method name="getRoleDictionary">
			<query>
        <![CDATA[
        SELECT  role FROM ${beanSecuritePack}.RoleBean AS role
       ]]>
			</query>
		</query-method>
		<query-method name="getApplicationDictionary">
			<query>
        <![CDATA[
        SELECT  application FROM ${beanDecoupagePack}.application.beans.ApplicationBean AS application 
        left join fetch application.logoFile 
        left join fetch application.payBean  
        WHERE application.id=1
       ]]>
			</query>
		</query-method>
		<query-method name="getDeviseDictionary">
			<query>
        <![CDATA[
        SELECT  devise FROM ${beanDevisePack}.DeviseBean AS devise
       ]]>
			</query>
		</query-method>
		<query-method name="getUserTypeDictionary">
			<query>
        <![CDATA[
        SELECT  userType FROM ${beanGraphiquePack}.userType.beans.UserTypeBean AS userType
       ]]>
			</query>
		</query-method>
		<query-method name="getToolActionDictionary">
			<query>
        <![CDATA[
        SELECT  toolAction FROM ${beanGraphiquePack}.toolAction.beans.ToolActionBean AS toolAction
       ]]>
			</query>
		</query-method>
		<query-method name="getListMenus">
			<query>
        <![CDATA[
        SELECT  menu FROM ${beanGraphiquePack}.menu.beans.MenuBean AS menu
       ]]>
			</query>
		</query-method>
		<query-method name="getActionTemplateDictionary">
			<query>
        <![CDATA[
        SELECT  actionTemplate FROM ${beanGraphiquePack}.actionTemplate.beans.ActionTemplateBean AS actionTemplate
       ]]>
			</query>
		</query-method>
		<query-method name="getMessageDictionary">
			<query>
        <![CDATA[
        SELECT  message FROM ${beanGraphiquePack}.message.beans.MessageBean AS message
       ]]>
			</query>
		</query-method>
	</dao-bean>
	<dao-bean name="userDao" interface="${daoPack}.UserDao">
		<query-method name="getUserBean" prefix-arg-name="arg">
			<query>
		        <![CDATA[
		        SELECT  userBean FROM ${beanUserPack}.UserBean AS userBean 
		          WHERE userBean.userName=:arg1.userName
		       ]]>
			</query>
		</query-method>
		<query-method name="getDisplayUser" class-resultat="${beanUserPack}.UserBean" prefix-arg-name="arg">
			<query>
		        <![CDATA[ 
		        SELECT  userBean.userId as userId,userBean.displayName as displayName,userBean.isActive as isActive FROM ${beanUserPack}.UserBean AS userBean WHERE userBean.userName=:arg1.userName
		        ]]>
			</query>
		</query-method>
		<query-method name="getOrganisation" prefix-arg-name="arg">
			<query>
		        <![CDATA[ 
		        SELECT bean   FROM tn.com.smartsoft.configGenerale.organisationSociete.organisation.beans.OrganismeBean AS bean 
		         left join fetch bean.parentSociete 
		        WHERE bean.id.organismeId=1 and  bean.id.societeId=1
		        ]]>
			</query>
		</query-method>
	</dao-bean>
	<dao-bean name="userMenuPreferenceDao" interface="${daoPack}.UserMenuPreferenceDao">
		<query-method name="getByCriteria" session-arg-rang="0" prefix-arg-name="arg">
			<query>
        <![CDATA[
        SELECT  userMenu FROM  ${beanUserPack}.UserMenuBean AS userMenu left join fetch userMenu.menuAction  AS menuAction WHERE 1=1
         <#if arg3.moduleId?exists >
             AND userMenu.id.moduleId=:arg3.moduleId
         </#if>
         <#if arg3.userId?exists >
             AND userMenu.id.userId=:arg3.userId
         </#if>
         ]]>
			</query>
		</query-method>
		<query-method name="getMenuAction" session-arg-rang="0" prefix-arg-name="arg">
			<query>
        <![CDATA[
        SELECT  menuAction FROM  tn.com.smartsoft.iap.dictionary.graphique.menuAction.beans.MenuActionBean AS menuAction left join fetch menuAction.parentMenu WHERE 1=1
         <#if arg3.moduleId?exists >
             AND menuAction.id.moduleId=:arg3.moduleId
         </#if>
         ]]>
			</query>
		</query-method>
		<query-method name="deleteUserMenu" session-arg-rang="0" prefix-arg-name="arg" is-updater="true">
			<query>
        <![CDATA[
            DELETE  FROM ${beanUserPack}.UserMenuBean AS bean WHERE bean.id.userId=:arg2.userId AND bean.id.moduleId=:arg2.moduleId
          ]]>
			</query>
		</query-method>
	</dao-bean>
	<business-bean name="applicationDictionnaireLoader" class="${businessPack}.ApplicationDictionnaireLoader">
		<set-dao-session name="daoSession" data-source-name="DefaultSession" />
		<set-dao-bean name="applicationDictionnaireDao" ref="applicationDictionnaireDao" />
		<set-dao-parse-bean name="entiteParser" ref="entite" />
		<set-dao-parse-bean name="menuParser" ref="menu" />
		<set-dao-parse-bean name="viewParser" ref="view" />
	</business-bean>
	<business-bean name="userBusiness" class="${businessPack}.UserBusiness">
		<set-property name="passwordHashing" ref="passwordHashing" />
		<set-dao-bean name="userDao" ref="userDao" />
		<set-dao-session name="daoSession" data-source-name="DefaultSession" />
	</business-bean>
	<business-bean name="userMenuPreferenceBusiness" class="${businessPack}.UserMenuPreferenceBusiness">
		<set-dao-bean name="entiteDao" ref="userMenuPreferenceDao" />
		<set-dao-session name="daoSession" data-source-name="DefaultSession" />
	</business-bean>
	<controler-bean name="defaultControler" class="${controlerPack}.DefaultControler"></controler-bean>
	<controler-bean name="userAccesControler" class="${controlerPack}.UserAccesControler">
		<set-business-bean name="userBusiness" ref="userBusiness" />
	</controler-bean>
	<controler-bean name="userMenuPreferenceControler" class="${controlerPack}.UserMenuPreferenceControler">
		<set-business-bean name="userMenuPreferenceBusiness" ref="userMenuPreferenceBusiness" />
	</controler-bean>
	<controler-bean name="updatePassWordControler" class="${controlerPack}.UpdatePassWordControler">
		<set-business-bean name="userBusiness" ref="userBusiness" />
	</controler-bean>
	<user-action-bean name="DefaultAction" home-window-id="homeWindow" model-class="${modelPack}.LoginModel" controler-bean="defaultControler">
		<binding-model name="userBean" mode="f" entite-id="User" type="${beanUserPack}.UserBean" />
		<window id="homeWindow" location="${viewPack}/defaultWindow.xml" view-id="Login"></window>
	</user-action-bean>
	<user-action-bean name="changeOrgAction" on-home-methode="changeOrganisme" model-class="${modelPack}.LoginModel" controler-bean="userAccesControler">
